ci:
  skip:
    - "pre-repro"
    # - "hide-notebook-inputs"
    - "update-warning-filters"
    # - "pyright"
    - "pytest-fast-only"
    # - "pytest-slow-only"
    - "fawltydeps"
    - "dvc-post-checkout"
    - "dvc-pre-push"
  autoupdate_schedule: "quarterly"

repos:
  - repo: "meta"
    hooks:
      # ? Enable this to ensure each hook runs against at least one file
      # - id: "check-hooks-apply"
      - id: "check-useless-excludes"
  - repo: "local"
    hooks:
      # * -------------------------------------------------------------------------- * #
      # * Changes below should persist in significant template updates.

      - id: "pre-repro"
        name: "pre-repro"
        language: "system"
        entry: "pwsh -Command python -m boilercv.pre_repro"
        files: |
          (?x)^(
            src/boilercv/models/.*
            |params.yaml
            |data/docs.dvc
          )$
        pass_filenames: false
        verbose: true
      # - id: "hide-notebook-inputs"
      #   name: "hide-notebook-inputs"
      #   pass_filenames: false
      #   language: "system"
      #   entry: "pwsh -Command python -m boilercv.docs"
      #   files: |
      #     (?x)^(
      #       docs/examples/.*
      #     )$

      # * -------------------------------------------------------------------------- * #
      # * Changes below may be lost in significant template updates.

      - id: "update-warning-filters"
        name: "update-warning-filters"
        verbose: true
        pass_filenames: false
        language: "system"
        entry: "pwsh -Command python warning_filters.py"
        files: |
          (?x)^(
            warning_filters.py
          )$
      # - id: "pyright"
      #   name: "pyright"
      #   pass_filenames: false
      #   language: "system"
      #   entry: "pwsh .tools/scripts/Invoke-Pyright.ps1"
      #   files: |
      #     (?x)^(
      #       src/.*
      #       |tests/.*
      #       |pyproject.toml
      #       |.tools/(
      #         pyproject.toml
      #         |requirements/.*
      #       )
      #     )$
      - id: "pytest-fast-only"
        name: "pytest-fast-only"
        verbose: true
        pass_filenames: false
        language: "system"
        entry: |
          pwsh -Command "pytest -m 'not slow' --suppress-no-test-exit-code"
        files: |
          (?x)^(
            pyproject.toml

            # exclude these if running pytest-slow-only again below
            src/.*
            |tests/.*

            |.tools/(
              pyproject.toml
              |requirements/.*
            )
          )$
      # - id: "pytest-slow-only"
      #   name: "pytest-slow-only"
      #   verbose: true
      #   pass_filenames: false
      #   language: "system"
      #   entry: |
      #     pwsh -Command "pytest -m 'slow' --suppress-no-test-exit-code"
      #   files: |
      #     (?x)^(
      #       src/.*
      #       |tests/.*
      #     )$
      - id: "fawltydeps"
        name: "fawltydeps"
        pass_filenames: false
        language: "system"
        entry: "pwsh -Command fawltydeps"
        files: |
          .*
  # * ------------------------------------------------------------------------------ * #
  # * Changes below should persist in significant template updates.

  - repo: "https://github.com/iterative/dvc"
    rev: "3.10.1"
    hooks:
      - id: "dvc-post-checkout"
        additional_dependencies: [".[gs]"]
      - id: "dvc-pre-push"
        additional_dependencies: [".[gs]"]

  # * ------------------------------------------------------------------------------ * #
  # * Changes below may be lost in significant template updates.

  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v4.4.0"
    hooks:
      - id: "end-of-file-fixer"
      - id: "trailing-whitespace"
  - repo: "https://github.com/DavidAnson/markdownlint-cli2"
    rev: "v0.8.1"
    hooks:
      - id: "markdownlint-cli2-fix"
  - repo: "https://github.com/psf/black"
    rev: "23.7.0"
    hooks:
      - id: "black"
      - id: "black-jupyter"
  - repo: "https://github.com/charliermarsh/ruff-pre-commit"
    rev: "v0.0.282"
    hooks:
      - id: "ruff"
  - repo: "https://github.com/srstevenson/nb-clean"
    rev: "2.4.0"
    hooks:
      - id: "nb-clean"
        args:
          - "--remove-empty-cells"
          - "--preserve-cell-metadata"
          - "special"
          - "tags"
          - "--"
        files: |
          (?x)^(
            src/.*
            |tests/.*
          )$
      - id: "nb-clean"
        name: "nb-clean (keep docs outputs)"
        args:
          - "--remove-empty-cells"
          - "--preserve-cell-outputs"
          - "--preserve-cell-metadata"
          - "special"
          - "tags"
          - "--"
        files: |
          (?x)^(
            docs/.*
          )$
  - repo: "https://github.com/asottile/blacken-docs"
    rev: "1.15.0"
    hooks:
      - id: "blacken-docs"
        additional_dependencies: ["black==23.7.0"]
  - repo: "https://github.com/nbQA-dev/nbQA"
    rev: "1.7.0"
    hooks:
      - id: "nbqa-ruff"
        additional_dependencies: ["ruff==0.0.282"]
