[build-system]
requires = [ "flit_core >=3.3,<4",]
build-backend = "flit_core.buildapi"

[project]
name = "boilercv"
requires-python = ">=3.11"
dependencies = [ "dvc[gs]>=2.46.0", "matplotlib>=3.7.1", "opencv-contrib-python>=4.7.0.72", "pandas>=1.5.3", "pandera>=0.13.4", "pyarrow>=11.0.0", "pydantic>=1.10.5", "pyjanitor>=0.24.0", "ruamel.yaml>=0.17.21", "seaborn>=0.12.2", "pyyaml>=6.0", "loguru>=0.6.0",]
readme = "README.md"
dynamic = [ "version", "description",]
[[project.authors]]
name = "Blake Naccarato"
email = "blake.naccarato+boilercv@gmail.com"

[project.urls]
Home = "https://github.com/blakeNaccarato/boilercv"

[tool.ruff]
fix = true
select = [ "ALL",]
src = [ "src", "tests",]
target-version = "py311"
extend-exclude = [ "template", "typings", ".github", ".tools", ".venv",]
ignore = [ "ANN", "ARG005", "C408", "COM", "D10", "D20", "D213", "DTZ", "E501", "EM", "ERA", "FBT", "INP001", "ISC", "PD013", "PD901", "PGH003", "RET", "TCH", "TRY003",]
unfixable = [ "F601",]

[tool.ruff.per-file-ignores]
"tests/**" = [ "ARG001", "S101",]

[tool.ruff.flake8-bugbear]
extend-immutable-calls = [ "typer.Argument", "typer.Option",]

[tool.ruff.pep8-naming]
classmethod-decorators = [ "pydantic.validator",]
