[build-system]
requires = [ "flit_core >=3.3,<4",]
build-backend = "flit_core.buildapi"

[project]
name = "boilercv"
version = "0.0.1"
description = "Computer vision routines suitable for nucleate pool boiling bubble analysis."
readme = "README.md"
requires-python = ">=3.11"
classifiers = [ "License :: OSI Approved :: MIT License",]
dependencies = [ "dvc[gs]>=3.5.1", "imageio[pyav]>=2.31.1", "ipywidgets>=8.0.7", "loguru>=0.7.0", "matplotlib>=3.7.2", "opencv-contrib-python>=4.8.0.74", "pandas[hdf5,performance]>=2.0.3", "pandera>=0.15.2", "pillow>=10.0.0", "pyarrow>=12.0.1", "pydantic>=1.10.11", "pyjanitor>=0.24.0", "pyqtgraph>=0.13.3", "pyside6>=6.5.1.1", "pytz>=2023.3", "pyyaml>=6.0", "ruamel.yaml>=0.17.32", "scikit-image>=0.21.0", "scipy>=1.11.1", "seaborn>=0.12.2", "sparklines>=0.4.2", "sympy>=1.12", "trackpy>=0.6.1", "xarray[accel,io,parallel]>=2023.6.0", "numpy>=1.24.4",]
[[project.authors]]
name = "Blake Naccarato, Kwang Jin Kim"
email = "blake.naccarato@gmail.com"

[project.license]
file = "LICENSE"

[project.urls]
Changes = "https://blakeNaccarato.github.io/boilercv/changelog.html"
Docs = "https://blakeNaccarato.github.io/boilercv"
Home = "https://github.com/blakeNaccarato/boilercv"
Tracker = "https://github.com/blakeNaccarato/boilercv/issues"

[tool.ruff]
fix = true
select = [ "ALL",]
src = [ "src", "tests",]
target-version = "py311"
extend-exclude = [ "template", "typings", ".github", ".tools", ".venv",]
ignore = [ "ANN", "ARG005", "C408", "COM", "D10", "D20", "D213", "D402", "DTZ", "E501", "EM", "ERA", "FBT", "F841", "G0", "INP001", "ISC", "PD013", "PD901", "PD011", "PGH003", "PIE804", "PLR0913", "PLR2004", "PLW2901", "RET", "S301", "TCH", "TD", "TRY003", "W2", "B018", "F821", "S101", "T201",]
unfixable = [ "F601",]

[tool.ruff.pydocstyle]
convention = "google"

[tool.ruff.isort]
split-on-trailing-comma = false

[tool.ruff.per-file-ignores]
"docs/**" = [ "E402",]
"tests/**" = [ "N815", "ARG001", "S101",]

[tool.ruff.flake8-bugbear]
extend-immutable-calls = [ "typer.Argument", "typer.Option",]

[tool.ruff.pep8-naming]
classmethod-decorators = [ "pydantic.validator",]
