florschuetz_chao_1965 = [1.000000, 0.946808, 0.924775, 0.907868, 0.893615, 0.881058, 0.869706, 0.859266, 0.849549, 0.840423]
isenberg_sideman_1970 = [1.000000, 0.993721, 0.987423, 0.981104, 0.974765, 0.968405, 0.962025, 0.955623, 0.949199, 0.942754]
akiyama_1973 = [1.000000, 0.995887, 0.991767, 0.987641, 0.983507, 0.979367, 0.975220, 0.971065, 0.966903, 0.962735]
yuan_et_al_2009 = [1.000000, 0.993324, 0.986629, 0.979915, 0.973182, 0.966430, 0.959657, 0.952864, 0.946051, 0.939217]
al_issa_et_al_2014 = [1.000000, 0.995927, 0.991853, 0.987776, 0.983698, 0.979618, 0.975536, 0.971452, 0.967367, 0.963279]
chen_mayinger_1992 = [1.000000, 0.992964, 0.985922, 0.978875, 0.971822, 0.964764, 0.957700, 0.950630, 0.943554, 0.936472]
inaba_et_al_2013 = [1.000000, 0.967928, 0.935857, 0.903785, 0.871714, 0.839642, 0.807571, 0.775499, 0.743427, 0.711356]
kalman_mori_2002 = [1.000000, 0.999766, 0.999532, 0.999299, 0.999065, 0.998831, 0.998597, 0.998363, 0.998129, 0.997895]
kim_park_2011 = [1.000000, 0.992802, 0.985589, 0.978359, 0.971114, 0.963852, 0.956574, 0.949279, 0.941967, 0.934638]
lucic_mayinger_2010 = [1.000000, 0.973078, 0.946156, 0.919233, 0.892311, 0.865389, 0.838467, 0.811545, 0.784622, 0.757700]
tang_et_al_2016 = [1.000000, 0.927931, 0.853450, 0.776152, 0.695500, 0.610738, 0.520744, 0.423701, 0.316231, 0.190162]
