name: "main"

on: ["workflow_dispatch"]

jobs:
  pyright:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "blakeNaccarato/copier-python-workflow-setup@v0.2.3"
        with:
          python-version: "3.11"
      - run: pyright
  ruff:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "blakeNaccarato/copier-python-workflow-setup@v0.2.3"
        with:
          python-version: "3.11"
      - run: "ruff --no-fix --output-format github ."
  pytest:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "blakeNaccarato/copier-python-workflow-setup@v0.2.3"
        with:
          python-version: "3.11"
      # * -------------------------------------------------------------------------- * #
      - name: Install PySide6 system dependencies
        run: |
          # https://askubuntu.com/questions/900285/libegl-so-1-is-not-a-symbolic-link
          sudo apt update
          sudo apt install libegl1
      # * -------------------------------------------------------------------------- * #
      # ! Need to specify `cov-config` as below.
      # ! See https://github.com/pytest-dev/pytest-cov/issues/479#issuecomment-1247444988
      - run: "pytest --cov --cov-config=pyproject.toml"
      - uses: "codecov/codecov-action@v3.1.4"
  fawltydeps:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "blakeNaccarato/copier-python-workflow-setup@v0.2.3"
        with:
          python-version: "3.11"
      - run: "fawltydeps"
  bump_project:
    needs: ["pyright", "ruff", "pytest", "fawltydeps"]
    runs-on: "ubuntu-latest"
    steps:
      - uses: "blakeNaccarato/copier-python-workflow-setup@v0.2.3"
        with:
          python-version: "3.11"
          install-project: false
      - uses: "stefanzweifel/git-auto-commit-action@v5.0.0"
        with:
          commit_message: "Update project."
