name: "main"

on: ["workflow_dispatch", "push"]

jobs:
  changes:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "dorny/paths-filter@v2"
        id: "filter"
        with:
          filters: |
            template:
              - "template/**"
    outputs:
      template: "${{ steps.filter.outputs.template }}"
  bump_template:
    needs: "changes"
    if: "${{ needs.changes.outputs.template == 'true' }}"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v4"
        with:
          python-version: "3.11"
      - run: |-
          python -m pip install -U pip
          pip install -U setuptools wheel
          pip install copier
          copier -f -r $(git rev-parse HEAD:template)
      - uses: "stefanzweifel/git-auto-commit-action@v4"
        with:
          commit_message: "Update repo to latest template"
  ruff:
    needs: "bump_template"
    if: "${{ !failure() }}"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "blakeNaccarato/copier-python-workflow-setup@v0.0.11"
        with:
          python-version: "3.11"
      - run: "ruff check --no-fix ."
  pyright:
    needs: "bump_template"
    if: "${{ !failure() }}"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "blakeNaccarato/copier-python-workflow-setup@v0.0.11"
        with:
          python-version: "3.11"
      - run: "pyright"
  pytest-cov:
    permissions:
      contents: "read"
      id-token: "write"
    needs: "bump_template"
    if: "${{ !failure() }}"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "blakeNaccarato/copier-python-workflow-setup@v0.0.11"
        with:
          python-version: "3.11"
      - uses: "google-github-actions/auth@v1.0.0"
        with:
          workload_identity_provider: "projects/326920613558/locations/global/workloadIdentityPools/github-com/providers/github-com-oidc"
          service_account: "iterative-studio@secure-garden-355020.iam.gserviceaccount.com"
      - uses: "google-github-actions/setup-gcloud@v1.1.0"
      - run: "dvc pull"
        env:
          GH_TOKEN: ${{ github.token }}
      - run: "pytest --cov"
        env:
          OPENCV_SAMPLES_DATA_PATH: data/samples_data
      - uses: "codecov/codecov-action@v3.1.1"
