name: "main"

on: ["push", "workflow_dispatch"]

jobs:
  # * ------------------------------------------------------------------------------ * #
  # * Changes below may be lost in significant template updates.

  pyright:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "blakeNaccarato/copier-python-workflow-setup@v0.2.3"
        with:
          python-version: "3.11"
      - run: ".tools/scripts/Invoke-Pyright.ps1"
        shell: "pwsh"
  ruff:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "blakeNaccarato/copier-python-workflow-setup@v0.2.3"
        with:
          python-version: "3.11"
      - run: "ruff --no-fix --output-format github ."
  pytest:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "blakeNaccarato/copier-python-workflow-setup@v0.2.3"
        with:
          python-version: "3.11"
      - name: Install PySide6 system dependencies
        run: |
          # https://askubuntu.com/questions/900285/libegl-so-1-is-not-a-symbolic-link
          sudo apt update
          sudo apt install libegl1
      - run: "pytest --cov"
      - uses: "codecov/codecov-action@v3.1.4"
  bump_project:
    needs: ["pyright", "ruff", "pytest"]
    runs-on: "ubuntu-latest"
    steps:
      - uses: "blakeNaccarato/copier-python-workflow-setup@v0.2.3"
        with:
          python-version: "3.11"
          install-project: false
      - uses: "stefanzweifel/git-auto-commit-action@v5.0.0"
        with:
          commit_message: "Update project."

  # * ------------------------------------------------------------------------------ * #
  # * Changes below should persist in significant template updates.
