name: "main"

on: ["push", "workflow_dispatch"]

jobs:
  # * ------------------------------------------------------------------------------ * #
  # * Changes below may be lost in significant template updates.

  pyright:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "blakeNaccarato/copier-python-workflow-setup@v0.0.12"
        with:
          python-version: "3.11"
      - run: "pyright"
  pytest-cov:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "blakeNaccarato/copier-python-workflow-setup@v0.0.12"
        with:
          python-version: "3.11"
      - uses: "google-github-actions/auth@v1.0.0"
        with:
          workload_identity_provider: "{{ secrets.workload_identity_provider }}"
          service_account: "{{ secrets.service_account }}"
      - uses: "google-github-actions/setup-gcloud@v1.1.0"
      - run: "dvc pull"
        env:
          GH_TOKEN: ${{ github.token }}
      - run: "pytest --cov"
        env:
          OPENCV_SAMPLES_DATA_PATH: data/samples_data
      - uses: "codecov/codecov-action@v3.1.1"

  # * ------------------------------------------------------------------------------ * #
  # * Changes below should persist in significant template updates.
